import type { Exercise } from "../types";
import { giphy } from "./giphy";

export const exercises: Record<string, Exercise> = {
  "db-seated-overhead-press": {
    id: "db-seated-overhead-press",
    name: "DB Seated Overhead Press",
    muscleGroup: "shoulders",
    type: "weighted",
    equipment: "Adjustable bench + dumbbells",
    gifId: "0404",
    description: "The dumbbell seated shoulder press is a strength exercise targeting the deltoid muscles of the shoulders. It is performed while seated, pressing dumbbells overhead to build shoulder and upper arm strength.",
    instructions: [
      "Sit on a bench with a dumbbell in each hand, resting on your thighs.",
      "Raise the dumbbells to shoulder height, palms facing forward.",
      "Press the dumbbells upward until your arms are fully extended overhead.",
      "Pause for a moment at the top, then slowly lower the dumbbells back to shoulder height.",
      "Repeat for the desired number of repetitions.",
    ],
  },
  "cable-lateral-raise-low": {
    id: "cable-lateral-raise-low",
    name: "Cable Lateral Raise (low pulley)",
    muscleGroup: "shoulders",
    type: "weighted",
    equipment: "Functional trainer, low pulley",
    gifId: "0178",
    description: "The cable lateral raise is an isolation exercise that targets the deltoid muscles, particularly the lateral (middle) head. It is performed using a cable machine, which provides constant tension throughout the movement.",
    instructions: [
      "Stand with your feet shoulder-width apart and grasp the cable handles with an overhand grip.",
      "Keep your arms straight and your core engaged.",
      "Raise your arms out to the sides until they are parallel to the floor.",
      "Pause for a moment at the top, then slowly lower your arms back down to the starting position.",
      "Repeat for the desired number of repetitions.",
    ],
  },
  "smith-upright-row": {
    id: "smith-upright-row",
    name: "Smith Machine Upright Row",
    muscleGroup: "shoulders",
    type: "weighted",
    equipment: "Smith machine",
    gifId: "0120",
    description: "The smith upright row targets the deltoids and also engages the traps and biceps. It involves pulling a barbell upwards towards the chin while keeping the elbows higher than the wrists.",
    instructions: [
      "Stand with your feet shoulder-width apart, facing the smith machine.",
      "Grasp the barbell with an overhand grip, hands slightly wider than shoulder-width apart.",
      "Keep your back straight and your core engaged.",
      "Pull the barbell up towards your chin, leading with your elbows.",
      "Pause for a moment at the top, then slowly lower the barbell back down to the starting position.",
      "Repeat for the desired number of repetitions.",
    ],
  },
  "cable-rear-delt-fly-high": {
    id: "cable-rear-delt-fly-high",
    name: "Cable Rear Delt Fly (high pulley)",
    muscleGroup: "rear delts",
    type: "weighted",
    equipment: "Functional trainer, high pulley",
    gifId: "0202",
    description: "The cable rear delt fly targets the rear deltoids, with secondary emphasis on the trapezius, rhomboids, and biceps. It uses a cable machine to provide constant tension throughout the movement.",
    instructions: [
      "Attach a rope handle to a low pulley cable machine.",
      "Stand facing the machine with your feet shoulder-width apart.",
      "Grasp the rope handle with an overhand grip, palms facing each other.",
      "Bend your knees slightly and hinge forward at the hips, keeping your back straight.",
      "Keep your elbows slightly bent and pull the rope towards your chest, squeezing your shoulder blades together.",
      "Pause for a moment at the top, then slowly return to the starting position.",
      "Repeat for the desired number of repetitions.",
    ],
  },
  "lying-cable-curl": {
    id: "lying-cable-curl",
    name: "Lying Cable Curl",
    muscleGroup: "biceps",
    type: "weighted",
    equipment: "Cable machine",
    gifId: "0182",
    description: "The lying cable curl is performed lying flat on a bench set in front of a low cable pulley. The cable provides constant tension throughout the movement, increasing the stretch and time under tension on the biceps.",
    instructions: [
      "Set a flat bench in front of a low cable pulley and lie face-up on it, head toward the machine.",
      "Grasp the cable attachment with both hands, arms fully extended toward the pulley, palms facing up.",
      "Keeping your upper arms stationary, exhale and curl the handle toward your shoulders.",
      "Squeeze your biceps at the top of the movement.",
      "Inhale and slowly lower back to the starting position.",
      "Repeat for the desired number of repetitions.",
    ],
  },
  "db-incline-curl": {
    id: "db-incline-curl",
    name: "DB Incline Curl",
    muscleGroup: "biceps",
    type: "weighted",
    equipment: "Adjustable bench + dumbbells",
    gifId: "0317",
    description: "The dumbbell incline biceps curl is performed on an incline bench to increase the stretch and activation of the biceps muscle. It also engages the forearms as secondary muscles.",
    instructions: [
      "Sit on an incline bench with a dumbbell in each hand, palms facing forward, and arms fully extended.",
      "Keeping your upper arms stationary, exhale and curl the weights while contracting your biceps.",
      "Continue to raise the dumbbells until your biceps are fully contracted and the dumbbells are at shoulder level.",
      "Hold the contracted position for a brief pause as you squeeze your biceps.",
      "Inhale and slowly begin to lower the dumbbells back to the starting position.",
      "Repeat for the desired number of repetitions.",
    ],
  },
  "cable-overhead-tricep-extension-low": {
    id: "cable-overhead-tricep-extension-low",
    name: "Cable Overhead Tricep Extension (low pulley)",
    muscleGroup: "triceps",
    type: "weighted",
    equipment: "Functional trainer, low pulley",
    gifId: "0194",
    description: "The cable overhead triceps extension targets the triceps using a cable machine and rope attachment. It requires extending the arms overhead, emphasizing the long head of the triceps.",
    instructions: [
      "Attach a rope to a cable machine at a high position.",
      "Stand facing away from the machine with your feet shoulder-width apart.",
      "Grasp the rope with both hands, palms facing each other, and bring your hands above your head.",
      "Keep your upper arms close to your head and your elbows pointing forward.",
      "Slowly lower the rope behind your head by bending your elbows.",
      "Pause for a moment, then extend your arms back up to the starting position.",
      "Repeat for the desired number of repetitions.",
    ],
  },
  "db-hammer-curl": {
    id: "db-hammer-curl",
    name: "DB Hammer Curl",
    muscleGroup: "biceps",
    type: "weighted",
    equipment: "Dumbbells",
    gifId: "0312",
    description: "The dumbbell hammer curl targets the biceps and forearms using a neutral grip (palms facing each other), which emphasizes the brachialis and brachioradialis muscles.",
    instructions: [
      "Stand up straight with a dumbbell in each hand, palms facing your torso.",
      "Keep your elbows close to your torso throughout the movement.",
      "Exhale and curl the weights while contracting your biceps.",
      "Continue to raise the weights until your biceps are fully contracted and the dumbbells are at shoulder level.",
      "Hold the contracted position for a brief pause as you squeeze your biceps.",
      "Inhale and slowly begin to lower the dumbbells back to the starting position.",
      "Repeat for the desired number of repetitions.",
    ],
  },
  "cable-tricep-pushdown": {
    id: "cable-tricep-pushdown",
    name: "Cable Tricep Pushdown",
    muscleGroup: "triceps",
    type: "weighted",
    equipment: "Functional trainer, rope attachment",
    gifId: "0200",
    description: "The cable pushdown with rope attachment is an isolation exercise targeting the triceps. It focuses on extending the elbows to work the triceps while also engaging the forearms.",
    instructions: [
      "Attach a rope attachment to a high pulley on a cable machine.",
      "Stand facing the machine with your feet shoulder-width apart and a slight bend in your knees.",
      "Grasp the rope with an overhand grip, palms facing each other.",
      "Keep your elbows close to your sides and your upper arms stationary throughout the exercise.",
      "Exhale and push the rope downward by extending your elbows until your arms are fully extended.",
      "Pause for a moment, then inhale and slowly return to the starting position.",
      "Repeat for the desired number of repetitions.",
    ],
  },
  "barbell-back-squat": {
    id: "barbell-back-squat",
    name: "Barbell Back Squat",
    muscleGroup: "quads",
    type: "weighted",
    equipment: "Squat station",
    gifId: null,
    description: "The barbell back squat is a compound lower body exercise that primarily targets the quads and glutes, with significant involvement from the hamstrings, calves, and core.",
    instructions: [
      "Stand with your feet shoulder-width apart, toes slightly turned out.",
      "Place the barbell on your upper back, resting it on your traps.",
      "Engage your core and keep your chest up as you begin to squat down, pushing your hips back and bending your knees.",
      "Lower yourself until your thighs are parallel to the ground, or as low as you can comfortably go.",
      "Drive through your heels to stand back up, extending your hips and knees.",
      "Repeat for the desired number of repetitions.",
    ],
  },
  "db-romanian-deadlift": {
    id: "db-romanian-deadlift",
    name: "DB Romanian Deadlift",
    muscleGroup: "hamstrings",
    type: "weighted",
    equipment: "Dumbbells",
    gifId: "1459",
    description: "The dumbbell Romanian deadlift targets the glutes, hamstrings, and lower back. It involves hinging at the hips while holding dumbbells, emphasizing posterior chain development.",
    instructions: [
      "Stand with your feet shoulder-width apart, holding a dumbbell in each hand with an overhand grip.",
      "Keeping your back straight and your core engaged, hinge at the hips and lower the dumbbells towards the ground, allowing your knees to bend slightly.",
      "Lower the dumbbells until you feel a stretch in your hamstrings.",
      "Push through your heels and engage your glutes to return to the starting position.",
      "Repeat for the desired number of repetitions.",
    ],
  },
  "leg-extension": {
    id: "leg-extension",
    name: "Leg Extension",
    muscleGroup: "quads",
    type: "weighted",
    equipment: "Adjustable bench leg extension attachment",
    gifId: "0585",
    description: "The leg extension is an isolation exercise that targets the quadriceps. It involves extending the knees to lift a weight, primarily working the front of the thighs.",
    instructions: [
      "Adjust the seat height and backrest of the machine to fit your body.",
      "Sit on the machine with your back against the backrest and your feet on the footpad.",
      "Grasp the handles or sidebars for stability.",
      "Extend your legs forward by straightening your knees, lifting the weight.",
      "Pause for a moment at the top, then slowly lower the weight back to the starting position.",
      "Repeat for the desired number of repetitions.",
    ],
  },
  "db-bulgarian-split-squat": {
    id: "db-bulgarian-split-squat",
    name: "DB Bulgarian Split Squat",
    muscleGroup: "quads",
    type: "weighted",
    equipment: "Adjustable bench + dumbbells",
    gifId: null,
    gifUrl: giphy.dbBulgarianSplitSquat,
    description: "The dumbbell Bulgarian split squat is a unilateral lower body exercise that targets the quadriceps, with secondary emphasis on the glutes and hamstrings. One leg is elevated on a bench.",
    instructions: [
      "Stand with your feet shoulder-width apart, holding a dumbbell in each hand.",
      "Take a step forward with one foot and position your back foot elevated on a bench or step.",
      "Lower your body by bending your front knee and hip, keeping your back knee slightly bent.",
      "Continue lowering until your front thigh is parallel to the ground.",
      "Push through your front heel to return to the starting position.",
      "Repeat for the desired number of repetitions, then switch legs.",
    ],
  },
  "cable-pull-through-low": {
    id: "cable-pull-through-low",
    name: "Cable Pull-Through (low pulley)",
    muscleGroup: "glutes",
    type: "weighted",
    equipment: "Functional trainer, low pulley",
    gifId: "0196",
    description: "The cable pull through is a hip hinge exercise that targets the glutes, with secondary emphasis on the hamstrings and lower back. It focuses on hip extension and posterior chain activation.",
    instructions: [
      "Stand facing away from the cable machine with your feet shoulder-width apart.",
      "Grab the rope attachment with both hands and step forward, creating tension in the cable.",
      "Bend at the hips and lower your upper body until it is parallel to the ground, keeping your back straight.",
      "Engage your glutes and hamstrings to pull your body back up to the starting position.",
      "Repeat for the desired number of repetitions.",
    ],
  },
  "cable-kneeling-crunch-high": {
    id: "cable-kneeling-crunch-high",
    name: "Cable Kneeling Crunch (high pulley)",
    muscleGroup: "core",
    type: "weighted",
    equipment: "Functional trainer, high pulley",
    gifId: "0175",
    description: "The cable kneeling crunch targets the abs and obliques using a cable machine with a rope attachment. It involves kneeling and crunching the torso down towards the thighs.",
    instructions: [
      "Attach a rope handle to a high pulley and kneel down facing away from the machine.",
      "Hold the rope handle with both hands and place it behind your head, keeping your elbows out to the sides.",
      "Keeping your hips stationary, flex your waist and crunch your torso down towards your thighs.",
      "Pause for a moment at the bottom, then slowly return to the starting position.",
      "Repeat for the desired number of repetitions.",
    ],
  },
  "plank-hold": {
    id: "plank-hold",
    name: "Plank Hold",
    muscleGroup: "core",
    type: "timed",
    equipment: "Bodyweight",
    gifId: "0464",
    gifUrl: giphy.plankHold,
    description: "The plank is a core stability exercise that challenges the abs, obliques, shoulders, and glutes. Hold a rigid straight-line position from head to heel.",
    instructions: [
      "Start in a forearm plank position with your elbows directly under your shoulders.",
      "Keep your body in a straight line from head to toe — no sagging hips.",
      "Engage your core and squeeze your glutes to maintain a stable position.",
      "Breathe steadily and hold for the target duration.",
      "To finish, lower your knees to the ground under control.",
    ],
  },
  "barbell-bench-press": {
    id: "barbell-bench-press",
    name: "Barbell Bench Press",
    muscleGroup: "chest",
    type: "weighted",
    equipment: "Squat/bench station",
    gifId: "0025",
    description: "The barbell bench press is a classic compound exercise that primarily targets the pectoral muscles, while also engaging the triceps and shoulders.",
    instructions: [
      "Lie flat on a bench with your feet flat on the ground and your back pressed against the bench.",
      "Grasp the barbell with an overhand grip slightly wider than shoulder-width apart.",
      "Lift the barbell off the rack and hold it directly above your chest with your arms fully extended.",
      "Lower the barbell slowly towards your chest, keeping your elbows tucked in.",
      "Pause for a moment when the barbell touches your chest.",
      "Push the barbell back up to the starting position by extending your arms.",
      "Repeat for the desired number of repetitions.",
    ],
  },
  "db-single-arm-row": {
    id: "db-single-arm-row",
    name: "DB Single-Arm Row",
    muscleGroup: "back",
    type: "weighted",
    equipment: "Adjustable bench + dumbbell",
    gifId: "0293",
    description: "The dumbbell one arm bent-over row targets the upper back, with secondary emphasis on the biceps and forearms. It involves hinging at the hips and pulling a dumbbell towards the chest.",
    instructions: [
      "Stand with your feet shoulder-width apart, holding a dumbbell in one hand with your palm facing your body.",
      "Bend your knees slightly and hinge forward at the hips, keeping your back straight and your core engaged.",
      "Let the dumbbell hang straight down towards the floor, with your arm fully extended.",
      "Pull the dumbbell up towards your chest, keeping your elbow close to your body and squeezing your shoulder blades together.",
      "Pause for a moment at the top, then slowly lower the dumbbell back down to the starting position.",
      "Repeat for the desired number of repetitions, then switch sides.",
    ],
  },
  "db-incline-bench-press": {
    id: "db-incline-bench-press",
    name: "Incline DB Press",
    muscleGroup: "chest",
    type: "weighted",
    equipment: "Adjustable bench + dumbbells",
    gifId: "0314",
    description: "The dumbbell incline bench press targets the upper portion of the pectoral muscles, with additional emphasis on the shoulders and triceps. It is performed on an incline bench.",
    instructions: [
      "Set up an incline bench at a 45-degree angle.",
      "Sit on the bench with your feet flat on the ground and your back pressed firmly against the bench.",
      "Hold a dumbbell in each hand, palms facing forward, and lift them to shoulder height.",
      "Slowly lower the dumbbells to the sides of your chest, keeping your elbows at a 90-degree angle.",
      "Push the dumbbells back up to the starting position, fully extending your arms.",
      "Repeat for the desired number of repetitions.",
    ],
  },
  "cable-seated-row-low": {
    id: "cable-seated-row-low",
    name: "Cable Seated Row (low pulley)",
    muscleGroup: "back",
    type: "weighted",
    equipment: "Functional trainer, low pulley",
    gifId: "0861",
    description: "The cable low seated row targets the upper back and also engages the biceps and forearms. The movement involves pulling the cable handles toward the torso while squeezing the shoulder blades together.",
    instructions: [
      "Sit on the machine with your feet flat on the footrests and your knees slightly bent.",
      "Grasp the handles with an overhand grip, palms facing down.",
      "Keep your back straight and lean slightly forward, maintaining a slight bend in your elbows.",
      "Pull the handles towards your body, squeezing your shoulder blades together.",
      "Pause for a moment at the peak of the movement, then slowly release back to the starting position.",
      "Repeat for the desired number of repetitions.",
    ],
  },
  "cable-chest-fly-high": {
    id: "cable-chest-fly-high",
    name: "Cable Chest Fly (high pulley)",
    muscleGroup: "chest",
    type: "weighted",
    equipment: "Functional trainer, high pulley",
    gifId: "0171",
    description: "The cable chest fly targets the pectoral muscles using a cable machine. It emphasizes a wide arc motion to stretch and contract the chest.",
    instructions: [
      "Set the pulleys to shoulder height on both sides of a cable machine.",
      "Stand in the center, grasp a handle in each hand with a slight bend in the elbows.",
      "Step forward slightly to create tension in the cables.",
      "With a controlled motion, bring your hands together in front of your chest in a wide arc.",
      "Pause for a moment at the peak contraction, then slowly return to the starting position.",
      "Repeat for the desired number of repetitions.",
    ],
  },
  "cable-face-pull-high": {
    id: "cable-face-pull-high",
    name: "Cable Face Pull (high pulley)",
    muscleGroup: "rear delts",
    type: "weighted",
    equipment: "Functional trainer, high pulley",
    gifId: null,
    gifUrl: giphy.cableFacePull,
    description: "The cable face pull targets the rear deltoids and external rotators of the shoulder, helping to improve posture and shoulder health.",
    instructions: [
      "Attach a rope to a high pulley cable machine.",
      "Stand facing the machine, grasp both ends of the rope with an overhand grip.",
      "Step back to create tension, keeping your feet shoulder-width apart.",
      "Pull the rope towards your face, separating your hands as they reach your ears.",
      "Squeeze your rear delts and external rotators at the peak.",
      "Slowly return to the starting position under control.",
      "Repeat for the desired number of repetitions.",
    ],
  },
  "kb-swing-light": {
    id: "kb-swing-light",
    name: "KB Swings (light, warmup)",
    muscleGroup: "full body",
    type: "weighted",
    equipment: "20 lb kettlebell",
    gifId: "0549",
    description: "The kettlebell swing is a dynamic exercise that targets the glutes and also engages the hamstrings and core. It involves swinging a kettlebell between the legs and up to shoulder height using hip drive.",
    instructions: [
      "Stand with your feet shoulder-width apart, toes pointed slightly outward.",
      "Hold the kettlebell with both hands in front of your body, arms extended.",
      "Bend your knees slightly and hinge at the hips, pushing your butt back.",
      "Swing the kettlebell back between your legs, keeping your arms straight and maintaining a flat back.",
      "Drive your hips forward and swing the kettlebell up to shoulder height using the momentum from your hips.",
      "Allow the kettlebell to swing back down between your legs and repeat.",
    ],
  },
  "battle-rope-alt-waves": {
    id: "battle-rope-alt-waves",
    name: "Battle Rope Alternating Waves",
    muscleGroup: "conditioning",
    type: "timed",
    equipment: "Battle rope",
    gifId: "0128",
    description: "Battle rope alternating waves is a high-intensity conditioning exercise that develops cardiovascular endurance, shoulder strength, and core stability.",
    instructions: [
      "Stand facing the anchor point with feet shoulder-width apart, knees slightly bent.",
      "Hold one end of the rope in each hand with an overhand grip.",
      "Raise one arm to shoulder height, then lower it as you raise the other arm.",
      "Alternate arms rapidly to create a wave pattern in the rope.",
      "Maintain a strong core and athletic stance throughout.",
      "Continue for the target duration.",
    ],
  },
  "dynamic-mobility": {
    id: "dynamic-mobility",
    name: "Dynamic Stretching / Mobility",
    muscleGroup: "mobility",
    type: "timed",
    equipment: "Bodyweight",
    gifId: null,
    description: "Dynamic stretching and mobility work prepares the body for exercise by increasing blood flow, improving range of motion, and activating key muscle groups.",
    instructions: [
      "Perform leg swings (front-to-back and side-to-side) for 10 reps each leg.",
      "Do hip circles, 10 rotations each direction.",
      "Perform arm circles, 10 forward and 10 backward.",
      "Do bodyweight squats with a 2-second pause at the bottom, 10 reps.",
      "Finish with 10 walkouts or inchworms to stretch the posterior chain.",
      "Move through each drill with control and full range of motion.",
    ],
  },
  "kb-swing-heavy": {
    id: "kb-swing-heavy",
    name: "KB Swings (heavy)",
    muscleGroup: "full body",
    type: "weighted",
    equipment: "35 lb kettlebell",
    gifId: "0549",
    description: "The heavy kettlebell swing develops explosive hip power, glute strength, and cardiovascular conditioning. Same mechanics as the light swing with greater load.",
    instructions: [
      "Stand with your feet shoulder-width apart, toes pointed slightly outward.",
      "Hold the kettlebell with both hands in front of your body, arms extended.",
      "Bend your knees slightly and hinge at the hips, pushing your butt back.",
      "Swing the kettlebell back between your legs, keeping your arms straight and maintaining a flat back.",
      "Drive your hips forward explosively and swing the kettlebell up to shoulder height.",
      "Allow the kettlebell to swing back down between your legs and repeat.",
    ],
  },
  "battle-rope-slams": {
    id: "battle-rope-slams",
    name: "Battle Rope Slams",
    muscleGroup: "conditioning",
    type: "timed",
    equipment: "Battle rope",
    gifId: null,
    description: "Battle rope slams are a power-based conditioning exercise targeting the shoulders, core, and full body, building explosive strength and cardiovascular endurance.",
    instructions: [
      "Stand facing the anchor point with feet shoulder-width apart, knees slightly bent.",
      "Hold both rope ends together with both hands overhead.",
      "Slam the ropes down to the ground as hard as possible.",
      "Immediately raise the ropes back overhead to full extension.",
      "Use your whole body — core, arms, and hips — to generate force.",
      "Continue for the target duration.",
    ],
  },
  "kb-goblet-squat": {
    id: "kb-goblet-squat",
    name: "KB Goblet Squat",
    muscleGroup: "quads",
    type: "weighted",
    equipment: "35 lb kettlebell",
    gifId: "0534",
    description: "The kettlebell goblet squat targets the glutes and quadriceps while holding a kettlebell close to the chest, making it great for building strength and improving squat technique.",
    instructions: [
      "Stand with your feet shoulder-width apart, holding a kettlebell close to your chest with both hands.",
      "Keeping your chest up and core engaged, lower your body into a squat by bending at the knees and hips.",
      "Continue lowering until your thighs are parallel to the ground, or as low as you can comfortably go.",
      "Pause for a moment at the bottom, then push through your heels to return to the starting position.",
      "Repeat for the desired number of repetitions.",
    ],
  },
  "smith-hip-thrust": {
    id: "smith-hip-thrust",
    name: "Smith Machine Hip Thrust",
    muscleGroup: "glutes",
    type: "weighted",
    equipment: "Smith machine, bench",
    gifId: null,
    description: "The Smith machine hip thrust is a loaded glute exercise performed with the upper back on a bench and the barbell across the hips. It maximally targets the glutes through hip extension.",
    instructions: [
      "Set the Smith machine bar to a height that allows it to rest across your hips when seated on the floor.",
      "Sit on the floor with your upper back against a bench, feet flat and knees bent at about 90 degrees.",
      "Roll the bar over your hips and pad it if needed.",
      "Drive through your heels and squeeze your glutes to thrust your hips up until your body forms a straight line from shoulders to knees.",
      "Pause and squeeze hard at the top, then lower under control.",
      "Repeat for the desired number of repetitions.",
    ],
  },
  "cable-glute-kickback-low": {
    id: "cable-glute-kickback-low",
    name: "Cable Glute Kickback (low pulley)",
    muscleGroup: "glutes",
    type: "weighted",
    equipment: "Functional trainer, low pulley, ankle strap",
    gifId: null,
    description: "The cable glute kickback isolates the glutes through hip extension with constant cable tension. An ankle strap attachment keeps the load on the glute throughout the full range.",
    instructions: [
      "Attach an ankle strap to the low pulley and fasten it around one ankle.",
      "Stand facing the machine, feet hip-width apart, and hold the frame for balance.",
      "Keeping a slight bend in your standing knee, kick the strapped leg back and up in a controlled arc.",
      "Squeeze the glute hard at the top of the movement.",
      "Slowly return to the starting position without letting your hip flex past neutral.",
      "Complete all reps on one side before switching.",
    ],
  },
  "ab-roller": {
    id: "ab-roller",
    name: "Ab Roller",
    muscleGroup: "core",
    type: "bodyweight",
    equipment: "Ab roller",
    gifId: "0084",
    description: "The ab roller rollout is a demanding core exercise that challenges the rectus abdominis, obliques, and hip flexors through a full extension and retraction of the torso.",
    instructions: [
      "Kneel on the floor and grip the ab roller handles with both hands directly below your shoulders.",
      "Brace your core and slowly roll the wheel forward, extending your body toward the floor.",
      "Keep your lower back flat — don't let it sag.",
      "Pause briefly at full extension, then exhale and pull the roller back to the starting position.",
      "Repeat for the desired number of repetitions.",
    ],
  },
  "hanging-knee-raise": {
    id: "hanging-knee-raise",
    name: "Hanging Knee Raise",
    muscleGroup: "core",
    type: "bodyweight",
    equipment: "Pull-up bar",
    gifId: "1761",
    description: "The hanging knee raise targets the lower abs and hip flexors. Performed from a dead hang, it requires controlled movement and a posterior pelvic tilt at the top to maximize abdominal engagement.",
    instructions: [
      "Grip a pull-up bar with an overhand grip, hands slightly wider than shoulder-width, and hang freely.",
      "Engage your core and, without swinging, raise your knees toward your chest.",
      "At the top, tilt your pelvis upward to fully contract the lower abs.",
      "Slowly lower your legs back to the starting position with control.",
      "Repeat for the desired number of repetitions.",
    ],
  },
  "reverse-lunge": {
    id: "reverse-lunge",
    name: "Reverse Lunge",
    muscleGroup: "legs",
    type: "bodyweight",
    equipment: "Dumbbells (optional)",
    gifId: "0381",
    description: "The reverse lunge is a unilateral lower-body exercise that targets the quads, glutes, and hamstrings. Stepping back reduces knee stress compared to a forward lunge.",
    instructions: [
      "Stand tall with feet hip-width apart, holding dumbbells at your sides if adding weight.",
      "Step one foot backward and lower your hips until both knees are bent to roughly 90 degrees.",
      "Keep your front knee behind your toes and your torso upright.",
      "Push through your front heel to return to standing.",
      "Alternate legs for the desired number of reps.",
    ],
  },
  "glute-bridge": {
    id: "glute-bridge",
    name: "Glute Bridge",
    muscleGroup: "glutes",
    type: "bodyweight",
    equipment: "Mat",
    gifId: null,
    gifUrl: giphy.gluteBridge,
    description: "The bodyweight glute bridge isolates the glutes and hamstrings through hip extension performed on the floor. It is a foundational movement for glute activation.",
    instructions: [
      "Lie on your back with knees bent, feet flat on the floor hip-width apart.",
      "Press your feet into the floor and drive your hips up until your body forms a straight line from knees to shoulders.",
      "Squeeze your glutes hard at the top and hold for a moment.",
      "Lower your hips back to the floor with control.",
      "Repeat for the desired number of repetitions.",
    ],
  },
  "wall-sit": {
    id: "wall-sit",
    name: "Wall Sit",
    muscleGroup: "legs",
    type: "bodyweight",
    equipment: "Wall",
    gifId: null,
    gifUrl: giphy.wallSit,
    description: "The wall sit is an isometric quad exercise performed by holding a seated position against a wall. It builds lower-body endurance and quad strength.",
    instructions: [
      "Stand with your back flat against a wall and feet shoulder-width apart, about two feet from the wall.",
      "Slide down until your hips and knees are at 90 degrees.",
      "Keep your back pressed into the wall and hold the position.",
      "Hold for the target duration.",
    ],
  },
  "squat-pulse": {
    id: "squat-pulse",
    name: "Squat Pulse",
    muscleGroup: "legs",
    type: "bodyweight",
    equipment: "Bodyweight",
    gifId: "3533",
    gifUrl: giphy.squatPulse,
    description: "The squat pulse keeps constant tension on the quads and glutes by holding at the bottom of a squat and pulsing through a small range of motion.",
    instructions: [
      "Lower into a squat until thighs are parallel to the floor.",
      "Hold at the bottom and pulse up and down a few inches continuously.",
      "Keep your chest up and core braced throughout.",
      "Continue for the target duration.",
    ],
  },
  "jump-squat": {
    id: "jump-squat",
    name: "Jump Squat",
    muscleGroup: "legs",
    type: "bodyweight",
    equipment: "Bodyweight",
    gifId: "0514",
    description: "The jump squat is a plyometric exercise that builds explosive power in the glutes, quads, and calves. Modify to a regular squat if needed.",
    instructions: [
      "Stand with feet shoulder-width apart.",
      "Lower into a squat, then explode upward, leaving the ground.",
      "Land softly with bent knees and immediately lower into the next squat.",
      "Modify to a regular squat if impact is an issue.",
      "Continue for the target duration.",
    ],
  },
  "high-knee": {
    id: "high-knee",
    name: "High Knees",
    muscleGroup: "full body",
    type: "bodyweight",
    equipment: "Bodyweight",
    gifId: "3655",
    gifUrl: giphy.highKnees,
    description: "High knees are a cardio exercise that drives the heart rate up while engaging the core, hip flexors, and legs. Drive each knee up to hip height at a rapid pace.",
    instructions: [
      "Stand tall with feet hip-width apart.",
      "Drive your right knee up toward your hip while swinging your left arm forward.",
      "Quickly switch, driving the left knee up.",
      "Maintain a fast pace and keep your core engaged.",
      "Continue for the target duration.",
    ],
  },
  "db-bent-over-row": {
    id: "db-bent-over-row",
    name: "DB Bent Over Row",
    muscleGroup: "back",
    type: "weighted",
    equipment: "Dumbbells",
    gifId: "0293",
    description: "The dumbbell bent over row targets the lats, rhomboids, and rear delts using a bilateral rowing motion. Hinging at the hips keeps constant tension on the back.",
    instructions: [
      "Hold a dumbbell in each hand, hinge at the hips until your torso is roughly parallel to the floor.",
      "Let the dumbbells hang directly below your shoulders with arms extended.",
      "Row both dumbbells toward your hips, squeezing your shoulder blades together.",
      "Lower with control back to the starting position.",
      "Repeat for the desired number of repetitions.",
    ],
  },
  "db-chest-press": {
    id: "db-chest-press",
    name: "DB Chest Press",
    muscleGroup: "chest",
    type: "weighted",
    equipment: "Dumbbells + flat bench",
    gifId: "0289",
    description: "The flat dumbbell chest press targets the pectorals, anterior deltoids, and triceps. Using dumbbells allows a greater range of motion than a barbell.",
    instructions: [
      "Lie on a flat bench holding a dumbbell in each hand at chest height, palms facing forward.",
      "Press the dumbbells up until your arms are fully extended, bringing them slightly together at the top.",
      "Lower the dumbbells back to chest height with control.",
      "Keep your feet flat on the floor and back slightly arched throughout.",
      "Repeat for the desired number of repetitions.",
    ],
  },
  "dead-bug": {
    id: "dead-bug",
    name: "Dead Bug",
    muscleGroup: "core",
    type: "bodyweight",
    equipment: "Mat",
    gifId: "0276",
    description: "The dead bug is a core stability exercise that trains the deep abdominal muscles and anti-extension strength by extending opposite arm and leg while keeping the lower back pressed to the floor.",
    instructions: [
      "Lie on your back with arms extended toward the ceiling and hips and knees at 90 degrees.",
      "Press your lower back firmly into the floor and brace your core.",
      "Slowly lower your right arm and left leg toward the floor while keeping your back flat.",
      "Return to the start and repeat on the opposite side.",
      "Perform the target reps per side.",
    ],
  },
  "russian-twist": {
    id: "russian-twist",
    name: "Russian Twist",
    muscleGroup: "core",
    type: "bodyweight",
    equipment: "Mat (weight optional)",
    gifId: "0687",
    gifUrl: giphy.russianTwist,
    description: "The Russian twist targets the obliques and rotational core strength. It is performed seated with feet raised and torso leaned back at a 45-degree angle.",
    instructions: [
      "Sit on the floor with knees bent, feet raised slightly, and torso leaned back at 45 degrees.",
      "Clasp your hands together or hold a weight at chest height.",
      "Rotate your torso to the right, then to the left — that's one rep.",
      "Keep your core braced and move with control.",
      "Repeat for the desired number of repetitions.",
    ],
  },
  "toe-touch": {
    id: "toe-touch",
    name: "Toe Touch",
    muscleGroup: "core",
    type: "bodyweight",
    equipment: "Mat",
    gifId: "3212",
    gifUrl: giphy.toeTouch,
    description: "The lying toe touch targets the upper abs by reaching both hands toward raised feet. It is a simple, low-impact core exercise that emphasizes the rectus abdominis.",
    instructions: [
      "Lie on your back and raise both legs to vertical, feet pointing toward the ceiling.",
      "Reach both hands upward toward your toes, lifting your shoulder blades off the floor.",
      "Hold the contracted position briefly, then lower your shoulders back down with control.",
      "Repeat for the desired number of repetitions.",
    ],
  },
  "glute-bridge-march": {
    id: "glute-bridge-march",
    name: "Glute Bridge March",
    muscleGroup: "glutes",
    type: "bodyweight",
    equipment: "Mat",
    gifId: "3561",
    description: "The glute bridge march builds unilateral glute and core stability by holding a bridge position and alternately lifting each foot off the floor.",
    instructions: [
      "Lie on your back and press into a glute bridge, hips fully extended.",
      "Brace your core and lift one foot a few inches off the floor, holding your hips level.",
      "Lower that foot and lift the other — that's one rep.",
      "Keep your hips from dropping or rotating throughout.",
      "Repeat for the desired number of repetitions.",
    ],
  },
  "bird-dog": {
    id: "bird-dog",
    name: "Bird Dog",
    muscleGroup: "core",
    type: "bodyweight",
    equipment: "Mat",
    gifId: null,
    gifUrl: giphy.birdDog,
    description: "The bird dog is a core stability exercise performed on all fours. It challenges anti-rotation strength and trains the deep spinal stabilizers by extending opposite arm and leg.",
    instructions: [
      "Start on all fours with wrists under shoulders and knees under hips.",
      "Brace your core and simultaneously extend your right arm forward and left leg back.",
      "Hold for a beat, keeping hips square and back flat.",
      "Return to the start and switch sides.",
      "Perform the target reps per side.",
    ],
  },
  "side-lying-leg-lift": {
    id: "side-lying-leg-lift",
    name: "Side Lying Leg Lift",
    muscleGroup: "glutes",
    type: "bodyweight",
    equipment: "Mat",
    gifId: "0710",
    description: "The side lying leg lift isolates the hip abductors and glute medius. It is a low-impact exercise commonly used in Pilates and glute activation routines.",
    instructions: [
      "Lie on your side with your body in a straight line, hips stacked.",
      "Rest your head on your bottom arm or hand.",
      "Keeping your top leg straight and foot flexed, lift it toward the ceiling.",
      "Hold briefly at the top, then lower with control.",
      "Complete all reps on one side before switching.",
    ],
  },
  "pilates-roll-up": {
    id: "pilates-roll-up",
    name: "Pilates Roll Up",
    muscleGroup: "core",
    type: "bodyweight",
    equipment: "Mat",
    gifId: "0456",
    gifUrl: giphy.pilatesRollUp,
    description: "The Pilates roll up is a controlled spinal flexion exercise that strengthens the abs and improves spinal mobility. It replaces momentum with deliberate muscle control.",
    instructions: [
      "Lie flat on your back with legs extended and arms reaching overhead.",
      "Inhale, then exhale as you slowly peel your spine off the mat, reaching forward toward your feet.",
      "At the top, take a breath, then slowly roll back down vertebra by vertebra.",
      "Keep the movement slow and controlled — avoid jerking or using momentum.",
      "Repeat for the desired number of repetitions.",
    ],
  },
  "fire-hydrant": {
    id: "fire-hydrant",
    name: "Fire Hydrant",
    muscleGroup: "glutes",
    type: "bodyweight",
    equipment: "Mat",
    gifId: "1774",
    gifUrl: giphy.fireHydrant,
    description: "The fire hydrant targets the glute medius and hip external rotators. Performed on all fours, it mimics the motion of a dog at a fire hydrant.",
    instructions: [
      "Start on all fours with wrists under shoulders and knees under hips.",
      "Keeping your knee bent at 90 degrees, lift one leg out to the side until it is parallel to the floor.",
      "Pause at the top, then lower with control.",
      "Complete all reps on one side before switching.",
      "Keep your hips level throughout the movement.",
    ],
  },
  "plank-shoulder-tap": {
    id: "plank-shoulder-tap",
    name: "Plank Shoulder Tap",
    muscleGroup: "core",
    type: "bodyweight",
    equipment: "Mat",
    gifId: "3699",
    description: "The plank shoulder tap builds anti-rotation core stability by maintaining a rigid plank position while alternately tapping each shoulder.",
    instructions: [
      "Start in a high plank position with wrists under shoulders and body in a straight line.",
      "Brace your core and, without rotating your hips, lift your right hand and tap your left shoulder.",
      "Return to the floor and repeat on the other side — that's one rep.",
      "Keep your feet slightly wider than hip-width to improve stability.",
      "Repeat for the desired number of repetitions.",
    ],
  },
  "db-thruster": {
    id: "db-thruster",
    name: "DB Thruster",
    muscleGroup: "full body",
    type: "weighted",
    equipment: "Dumbbells",
    gifId: "0550",
    description: "The dumbbell thruster combines a front squat and overhead press into one fluid movement. It is a high-intensity full-body exercise that challenges strength and conditioning simultaneously.",
    instructions: [
      "Hold a dumbbell in each hand at shoulder height, palms facing each other.",
      "Lower into a squat until thighs are parallel to the floor.",
      "As you drive up out of the squat, press the dumbbells overhead in one motion.",
      "Lower the dumbbells back to shoulders as you descend into the next squat.",
      "Continue for the target duration or reps.",
    ],
  },
  "mountain-climber": {
    id: "mountain-climber",
    name: "Mountain Climber",
    muscleGroup: "core",
    type: "bodyweight",
    equipment: "Bodyweight",
    gifId: "0630",
    description: "Mountain climbers are a dynamic core and cardio exercise performed in a plank position. Rapidly driving the knees toward the chest elevates the heart rate while building core and hip flexor strength.",
    instructions: [
      "Start in a high plank position with wrists under shoulders and core braced.",
      "Drive your right knee toward your chest, then quickly switch legs.",
      "Keep your hips level and don't let your lower back sag.",
      "Move at a controlled pace or as fast as form allows.",
      "Continue for the target duration.",
    ],
  },
  "renegade-row": {
    id: "renegade-row",
    name: "Renegade Row",
    muscleGroup: "back",
    type: "weighted",
    equipment: "Dumbbells",
    gifId: "0521",
    description: "The renegade row combines a plank hold with a unilateral dumbbell row, challenging core anti-rotation strength and back development simultaneously.",
    instructions: [
      "Start in a high plank with a dumbbell in each hand, feet slightly wider than hip-width.",
      "Brace your core hard and row one dumbbell to your hip, keeping your elbow close.",
      "Lower it back to the floor, then row the other side.",
      "Avoid rotating your hips — keep them square to the floor throughout.",
      "Continue for the target duration or reps.",
    ],
  },
  "skater-hop": {
    id: "skater-hop",
    name: "Skater Hop",
    muscleGroup: "legs",
    type: "bodyweight",
    equipment: "Bodyweight",
    gifId: "3361",
    description: "Skater hops are a lateral plyometric exercise that builds single-leg power, balance, and hip abductor strength. The side-to-side jumping motion mimics a speed skater's stride.",
    instructions: [
      "Stand on your right foot with a slight bend in your knee.",
      "Jump laterally to the left, landing softly on your left foot and swinging your right foot behind you.",
      "Immediately bound back to the right.",
      "Keep your chest up and land with a bent knee to absorb impact.",
      "Continue for the target duration.",
    ],
  },
  "db-deadlift-to-press": {
    id: "db-deadlift-to-press",
    name: "DB Deadlift to Press",
    muscleGroup: "full body",
    type: "weighted",
    equipment: "Dumbbells",
    gifId: "0028",
    description: "The dumbbell deadlift to press links a Romanian deadlift with an upright row and overhead press, training the posterior chain and shoulders in one compound movement.",
    instructions: [
      "Hold a dumbbell in each hand in front of your thighs.",
      "Hinge at the hips and lower the dumbbells toward the floor, keeping your back flat.",
      "Drive your hips forward to stand, using the momentum to pull the dumbbells up to shoulder height.",
      "Press the dumbbells overhead, then lower them back to shoulders and repeat the deadlift.",
      "Continue for the target duration or reps.",
    ],
  },
  "plank-jack": {
    id: "plank-jack",
    name: "Plank Jack",
    muscleGroup: "core",
    type: "bodyweight",
    equipment: "Bodyweight",
    gifId: null,
    gifUrl: giphy.plankJack,
    description: "Plank jacks combine a forearm plank hold with jumping jack leg movements, adding a cardio element to core stability training.",
    instructions: [
      "Start in a forearm plank with elbows under shoulders and body in a straight line.",
      "Jump both feet out wide, then back together — like a horizontal jumping jack.",
      "Keep your hips level and core braced throughout.",
      "Move at a pace that allows you to maintain good form.",
      "Continue for the target duration.",
    ],
  },
  "db-sumo-squat": {
    id: "db-sumo-squat",
    name: "DB Sumo Squat",
    muscleGroup: "legs",
    type: "weighted",
    equipment: "Dumbbell",
    gifId: "3142",
    gifUrl: giphy.dbSumoSquat,
    description: "The dumbbell sumo squat uses a wide stance with toes turned out to emphasize the inner thighs and glutes. A single dumbbell is held vertically between the legs.",
    instructions: [
      "Stand with feet wider than shoulder-width apart, toes turned out 45 degrees.",
      "Hold a single dumbbell vertically with both hands between your legs.",
      "Keeping your chest tall and knees tracking over your toes, lower until thighs are parallel to the floor.",
      "Drive through your heels to return to standing, squeezing your glutes at the top.",
      "Repeat for the desired number of repetitions.",
    ],
  },
  "curtsy-lunge": {
    id: "curtsy-lunge",
    name: "Curtsy Lunge",
    muscleGroup: "glutes",
    type: "bodyweight",
    equipment: "Dumbbells (optional)",
    gifId: null,
    gifUrl: giphy.curtsyLunge,
    description: "The curtsy lunge is a cross-body lunge variation that places extra emphasis on the glute medius and outer glutes compared to a standard lunge.",
    instructions: [
      "Stand with feet hip-width apart.",
      "Step your right foot diagonally behind and to the left, lowering into a lunge.",
      "Keep your front knee over your front foot and torso upright.",
      "Push through your front heel to return to standing.",
      "Complete all reps on one side before switching.",
    ],
  },
  "glute-bridge-pulse": {
    id: "glute-bridge-pulse",
    name: "Glute Bridge Pulse",
    muscleGroup: "glutes",
    type: "bodyweight",
    equipment: "Mat",
    gifId: "0484",
    gifUrl: giphy.gluteBridge,
    description: "The glute bridge pulse keeps constant tension on the glutes by holding at the top of a bridge and pulsing through a small range of motion.",
    instructions: [
      "Lie on your back with knees bent and feet flat on the floor.",
      "Drive your hips up into a bridge and hold near the top.",
      "Pulse your hips up and down a few inches, squeezing your glutes on each pulse.",
      "Don't fully lower between pulses — maintain tension throughout.",
      "Repeat for the desired number of repetitions.",
    ],
  },
  "bicycle-crunch": {
    id: "bicycle-crunch",
    name: "Bicycle Crunch",
    muscleGroup: "core",
    type: "bodyweight",
    equipment: "Mat",
    gifId: "0972",
    description: "The bicycle crunch targets the rectus abdominis and obliques through a simultaneous rotating and pedaling motion. It is one of the highest-activation ab exercises.",
    instructions: [
      "Lie on your back with hands behind your head and knees bent.",
      "Lift your shoulder blades off the floor and bring one knee toward your chest.",
      "Rotate your torso to bring the opposite elbow toward that knee while extending the other leg.",
      "Switch sides in a smooth pedaling motion.",
      "Count each side as one rep.",
    ],
  },
  "heel-tap": {
    id: "heel-tap",
    name: "Heel Tap",
    muscleGroup: "core",
    type: "bodyweight",
    equipment: "Mat",
    gifId: "0006",
    description: "Heel taps target the obliques through a side-to-side lateral crunch motion. Performed lying down, they are a low-impact option for oblique work.",
    instructions: [
      "Lie on your back with knees bent, feet flat on the floor, and arms at your sides.",
      "Lift your shoulder blades slightly off the floor.",
      "Reach your right hand down to tap your right heel by crunching laterally.",
      "Return to center and repeat on the left side — that's one rep.",
      "Repeat for the desired number of repetitions.",
    ],
  },
  "leg-raise": {
    id: "leg-raise",
    name: "Leg Raise",
    muscleGroup: "core",
    type: "bodyweight",
    equipment: "Mat",
    gifId: "0620",
    description: "The lying leg raise targets the lower abs and hip flexors. Keeping the legs straight and lowering them slowly maximizes tension on the abdominal muscles.",
    instructions: [
      "Lie flat on your back with legs extended and hands under your lower back for support.",
      "Keeping legs straight, raise them to vertical.",
      "Slowly lower your legs back toward the floor without letting them touch.",
      "Reverse and raise again.",
      "Repeat for the desired number of repetitions.",
    ],
  },
  "flutter-kick": {
    id: "flutter-kick",
    name: "Flutter Kick",
    muscleGroup: "core",
    type: "bodyweight",
    equipment: "Mat",
    gifId: "0459",
    gifUrl: giphy.flutterKicks,
    description: "Flutter kicks target the lower abs and hip flexors through rapid alternating leg movements performed while lying flat. They sustain continuous tension on the core.",
    instructions: [
      "Lie flat on your back with legs extended and hands under your glutes for support.",
      "Lift both legs a few inches off the floor.",
      "Rapidly alternate kicking each leg up and down in a small range of motion.",
      "Keep your lower back pressed into the floor throughout.",
      "Continue for the target duration.",
    ],
  },
  "kb-clean-press": {
    id: "kb-clean-press",
    name: "KB Single-Arm Clean & Press",
    muscleGroup: "full body",
    type: "weighted",
    equipment: "25 lb kettlebell",
    gifId: "0518",
    description: "The kettlebell single-arm clean and press is a full-body exercise combining a clean (pulling to the rack position) and an overhead press. It builds coordination, explosive power, and shoulder strength.",
    instructions: [
      "Stand with your feet shoulder-width apart, holding a kettlebell in one hand with an overhand grip.",
      "Bend your knees slightly and hinge forward at the hips, allowing the kettlebell to hang in front of you.",
      "In one fluid motion, explosively extend your hips, shrug your shoulder, and pull the kettlebell up towards your shoulder.",
      "As the kettlebell reaches shoulder height, rotate your wrist and catch it in the rack position (resting on the outside of your forearm).",
      "From the rack position, press the kettlebell overhead by extending your arm fully.",
      "Lower the kettlebell back to the rack position, then back to the starting position.",
      "Repeat for the desired number of repetitions, then switch arms.",
    ],
  },
};

export function getExercise(id: string) {
  const ex = exercises[id];
  if (!ex) throw new Error(`Unknown exercise: ${id}`);
  return ex;
}
