import type { Exercise } from "../types";

export const exercises: Record<string, Exercise> = {
  "db-seated-overhead-press": {
    id: "db-seated-overhead-press",
    name: "DB Seated Overhead Press",
    muscleGroup: "shoulders",
    type: "weighted",
    equipment: "Adjustable bench + dumbbells",
    exerciseDbId: "0404",
    description: "The dumbbell seated shoulder press is a strength exercise targeting the deltoid muscles of the shoulders. It is performed while seated, pressing dumbbells overhead to build shoulder and upper arm strength.",
    instructions: [
      "Sit on a bench with a dumbbell in each hand, resting on your thighs.",
      "Raise the dumbbells to shoulder height, palms facing forward.",
      "Press the dumbbells upward until your arms are fully extended overhead.",
      "Pause for a moment at the top, then slowly lower the dumbbells back to shoulder height.",
      "Repeat for the desired number of repetitions.",
    ],
  },
  "cable-lateral-raise-low": {
    id: "cable-lateral-raise-low",
    name: "Cable Lateral Raise (low pulley)",
    muscleGroup: "shoulders",
    type: "weighted",
    equipment: "Functional trainer, low pulley",
    exerciseDbId: "0178",
    description: "The cable lateral raise is an isolation exercise that targets the deltoid muscles, particularly the lateral (middle) head. It is performed using a cable machine, which provides constant tension throughout the movement.",
    instructions: [
      "Stand with your feet shoulder-width apart and grasp the cable handles with an overhand grip.",
      "Keep your arms straight and your core engaged.",
      "Raise your arms out to the sides until they are parallel to the floor.",
      "Pause for a moment at the top, then slowly lower your arms back down to the starting position.",
      "Repeat for the desired number of repetitions.",
    ],
  },
  "smith-upright-row": {
    id: "smith-upright-row",
    name: "Smith Machine Upright Row",
    muscleGroup: "shoulders",
    type: "weighted",
    equipment: "Smith machine",
    exerciseDbId: "0120",
    description: "The smith upright row targets the deltoids and also engages the traps and biceps. It involves pulling a barbell upwards towards the chin while keeping the elbows higher than the wrists.",
    instructions: [
      "Stand with your feet shoulder-width apart, facing the smith machine.",
      "Grasp the barbell with an overhand grip, hands slightly wider than shoulder-width apart.",
      "Keep your back straight and your core engaged.",
      "Pull the barbell up towards your chin, leading with your elbows.",
      "Pause for a moment at the top, then slowly lower the barbell back down to the starting position.",
      "Repeat for the desired number of repetitions.",
    ],
  },
  "cable-rear-delt-fly-high": {
    id: "cable-rear-delt-fly-high",
    name: "Cable Rear Delt Fly (high pulley)",
    muscleGroup: "rear delts",
    type: "weighted",
    equipment: "Functional trainer, high pulley",
    exerciseDbId: "0202",
    description: "The cable rear delt fly targets the rear deltoids, with secondary emphasis on the trapezius, rhomboids, and biceps. It uses a cable machine to provide constant tension throughout the movement.",
    instructions: [
      "Attach a rope handle to a low pulley cable machine.",
      "Stand facing the machine with your feet shoulder-width apart.",
      "Grasp the rope handle with an overhand grip, palms facing each other.",
      "Bend your knees slightly and hinge forward at the hips, keeping your back straight.",
      "Keep your elbows slightly bent and pull the rope towards your chest, squeezing your shoulder blades together.",
      "Pause for a moment at the top, then slowly return to the starting position.",
      "Repeat for the desired number of repetitions.",
    ],
  },
  "db-incline-curl": {
    id: "db-incline-curl",
    name: "DB Incline Curl",
    muscleGroup: "biceps",
    type: "weighted",
    equipment: "Adjustable bench + dumbbells",
    exerciseDbId: "0317",
    description: "The dumbbell incline biceps curl is performed on an incline bench to increase the stretch and activation of the biceps muscle. It also engages the forearms as secondary muscles.",
    instructions: [
      "Sit on an incline bench with a dumbbell in each hand, palms facing forward, and arms fully extended.",
      "Keeping your upper arms stationary, exhale and curl the weights while contracting your biceps.",
      "Continue to raise the dumbbells until your biceps are fully contracted and the dumbbells are at shoulder level.",
      "Hold the contracted position for a brief pause as you squeeze your biceps.",
      "Inhale and slowly begin to lower the dumbbells back to the starting position.",
      "Repeat for the desired number of repetitions.",
    ],
  },
  "cable-overhead-tricep-extension-low": {
    id: "cable-overhead-tricep-extension-low",
    name: "Cable Overhead Tricep Extension (low pulley)",
    muscleGroup: "triceps",
    type: "weighted",
    equipment: "Functional trainer, low pulley",
    exerciseDbId: "0194",
    description: "The cable overhead triceps extension targets the triceps using a cable machine and rope attachment. It requires extending the arms overhead, emphasizing the long head of the triceps.",
    instructions: [
      "Attach a rope to a cable machine at a high position.",
      "Stand facing away from the machine with your feet shoulder-width apart.",
      "Grasp the rope with both hands, palms facing each other, and bring your hands above your head.",
      "Keep your upper arms close to your head and your elbows pointing forward.",
      "Slowly lower the rope behind your head by bending your elbows.",
      "Pause for a moment, then extend your arms back up to the starting position.",
      "Repeat for the desired number of repetitions.",
    ],
  },
  "db-hammer-curl": {
    id: "db-hammer-curl",
    name: "DB Hammer Curl",
    muscleGroup: "biceps",
    type: "weighted",
    equipment: "Dumbbells",
    exerciseDbId: "0312",
    description: "The dumbbell hammer curl targets the biceps and forearms using a neutral grip (palms facing each other), which emphasizes the brachialis and brachioradialis muscles.",
    instructions: [
      "Stand up straight with a dumbbell in each hand, palms facing your torso.",
      "Keep your elbows close to your torso throughout the movement.",
      "Exhale and curl the weights while contracting your biceps.",
      "Continue to raise the weights until your biceps are fully contracted and the dumbbells are at shoulder level.",
      "Hold the contracted position for a brief pause as you squeeze your biceps.",
      "Inhale and slowly begin to lower the dumbbells back to the starting position.",
      "Repeat for the desired number of repetitions.",
    ],
  },
  "cable-tricep-pushdown": {
    id: "cable-tricep-pushdown",
    name: "Cable Tricep Pushdown",
    muscleGroup: "triceps",
    type: "weighted",
    equipment: "Functional trainer, rope attachment",
    exerciseDbId: "0200",
    description: "The cable pushdown with rope attachment is an isolation exercise targeting the triceps. It focuses on extending the elbows to work the triceps while also engaging the forearms.",
    instructions: [
      "Attach a rope attachment to a high pulley on a cable machine.",
      "Stand facing the machine with your feet shoulder-width apart and a slight bend in your knees.",
      "Grasp the rope with an overhand grip, palms facing each other.",
      "Keep your elbows close to your sides and your upper arms stationary throughout the exercise.",
      "Exhale and push the rope downward by extending your elbows until your arms are fully extended.",
      "Pause for a moment, then inhale and slowly return to the starting position.",
      "Repeat for the desired number of repetitions.",
    ],
  },
  "barbell-back-squat": {
    id: "barbell-back-squat",
    name: "Barbell Back Squat",
    muscleGroup: "quads",
    type: "weighted",
    equipment: "Squat station",
    exerciseDbId: null,
    description: "The barbell back squat is a compound lower body exercise that primarily targets the quads and glutes, with significant involvement from the hamstrings, calves, and core.",
    instructions: [
      "Stand with your feet shoulder-width apart, toes slightly turned out.",
      "Place the barbell on your upper back, resting it on your traps.",
      "Engage your core and keep your chest up as you begin to squat down, pushing your hips back and bending your knees.",
      "Lower yourself until your thighs are parallel to the ground, or as low as you can comfortably go.",
      "Drive through your heels to stand back up, extending your hips and knees.",
      "Repeat for the desired number of repetitions.",
    ],
  },
  "db-romanian-deadlift": {
    id: "db-romanian-deadlift",
    name: "DB Romanian Deadlift",
    muscleGroup: "hamstrings",
    type: "weighted",
    equipment: "Dumbbells",
    exerciseDbId: "1459",
    description: "The dumbbell Romanian deadlift targets the glutes, hamstrings, and lower back. It involves hinging at the hips while holding dumbbells, emphasizing posterior chain development.",
    instructions: [
      "Stand with your feet shoulder-width apart, holding a dumbbell in each hand with an overhand grip.",
      "Keeping your back straight and your core engaged, hinge at the hips and lower the dumbbells towards the ground, allowing your knees to bend slightly.",
      "Lower the dumbbells until you feel a stretch in your hamstrings.",
      "Push through your heels and engage your glutes to return to the starting position.",
      "Repeat for the desired number of repetitions.",
    ],
  },
  "leg-extension": {
    id: "leg-extension",
    name: "Leg Extension",
    muscleGroup: "quads",
    type: "weighted",
    equipment: "Adjustable bench leg extension attachment",
    exerciseDbId: "0585",
    description: "The leg extension is an isolation exercise that targets the quadriceps. It involves extending the knees to lift a weight, primarily working the front of the thighs.",
    instructions: [
      "Adjust the seat height and backrest of the machine to fit your body.",
      "Sit on the machine with your back against the backrest and your feet on the footpad.",
      "Grasp the handles or sidebars for stability.",
      "Extend your legs forward by straightening your knees, lifting the weight.",
      "Pause for a moment at the top, then slowly lower the weight back to the starting position.",
      "Repeat for the desired number of repetitions.",
    ],
  },
  "db-bulgarian-split-squat": {
    id: "db-bulgarian-split-squat",
    name: "DB Bulgarian Split Squat",
    muscleGroup: "quads",
    type: "weighted",
    equipment: "Adjustable bench + dumbbells",
    exerciseDbId: null,
    description: "The dumbbell Bulgarian split squat is a unilateral lower body exercise that targets the quadriceps, with secondary emphasis on the glutes and hamstrings. One leg is elevated on a bench.",
    instructions: [
      "Stand with your feet shoulder-width apart, holding a dumbbell in each hand.",
      "Take a step forward with one foot and position your back foot elevated on a bench or step.",
      "Lower your body by bending your front knee and hip, keeping your back knee slightly bent.",
      "Continue lowering until your front thigh is parallel to the ground.",
      "Push through your front heel to return to the starting position.",
      "Repeat for the desired number of repetitions, then switch legs.",
    ],
  },
  "cable-pull-through-low": {
    id: "cable-pull-through-low",
    name: "Cable Pull-Through (low pulley)",
    muscleGroup: "glutes",
    type: "weighted",
    equipment: "Functional trainer, low pulley",
    exerciseDbId: "0196",
    description: "The cable pull through is a hip hinge exercise that targets the glutes, with secondary emphasis on the hamstrings and lower back. It focuses on hip extension and posterior chain activation.",
    instructions: [
      "Stand facing away from the cable machine with your feet shoulder-width apart.",
      "Grab the rope attachment with both hands and step forward, creating tension in the cable.",
      "Bend at the hips and lower your upper body until it is parallel to the ground, keeping your back straight.",
      "Engage your glutes and hamstrings to pull your body back up to the starting position.",
      "Repeat for the desired number of repetitions.",
    ],
  },
  "cable-kneeling-crunch-high": {
    id: "cable-kneeling-crunch-high",
    name: "Cable Kneeling Crunch (high pulley)",
    muscleGroup: "core",
    type: "weighted",
    equipment: "Functional trainer, high pulley",
    exerciseDbId: "0175",
    description: "The cable kneeling crunch targets the abs and obliques using a cable machine with a rope attachment. It involves kneeling and crunching the torso down towards the thighs.",
    instructions: [
      "Attach a rope handle to a high pulley and kneel down facing away from the machine.",
      "Hold the rope handle with both hands and place it behind your head, keeping your elbows out to the sides.",
      "Keeping your hips stationary, flex your waist and crunch your torso down towards your thighs.",
      "Pause for a moment at the bottom, then slowly return to the starting position.",
      "Repeat for the desired number of repetitions.",
    ],
  },
  "plank-hold": {
    id: "plank-hold",
    name: "Plank Hold",
    muscleGroup: "core",
    type: "timed",
    equipment: "Bodyweight",
    exerciseDbId: "0464",
    description: "The plank is a core stability exercise that challenges the abs, obliques, shoulders, and glutes. Hold a rigid straight-line position from head to heel.",
    instructions: [
      "Start in a forearm plank position with your elbows directly under your shoulders.",
      "Keep your body in a straight line from head to toe — no sagging hips.",
      "Engage your core and squeeze your glutes to maintain a stable position.",
      "Breathe steadily and hold for the target duration.",
      "To finish, lower your knees to the ground under control.",
    ],
  },
  "barbell-bench-press": {
    id: "barbell-bench-press",
    name: "Barbell Bench Press",
    muscleGroup: "chest",
    type: "weighted",
    equipment: "Squat/bench station",
    exerciseDbId: "0025",
    description: "The barbell bench press is a classic compound exercise that primarily targets the pectoral muscles, while also engaging the triceps and shoulders.",
    instructions: [
      "Lie flat on a bench with your feet flat on the ground and your back pressed against the bench.",
      "Grasp the barbell with an overhand grip slightly wider than shoulder-width apart.",
      "Lift the barbell off the rack and hold it directly above your chest with your arms fully extended.",
      "Lower the barbell slowly towards your chest, keeping your elbows tucked in.",
      "Pause for a moment when the barbell touches your chest.",
      "Push the barbell back up to the starting position by extending your arms.",
      "Repeat for the desired number of repetitions.",
    ],
  },
  "db-single-arm-row": {
    id: "db-single-arm-row",
    name: "DB Single-Arm Row",
    muscleGroup: "back",
    type: "weighted",
    equipment: "Adjustable bench + dumbbell",
    exerciseDbId: "0293",
    description: "The dumbbell one arm bent-over row targets the upper back, with secondary emphasis on the biceps and forearms. It involves hinging at the hips and pulling a dumbbell towards the chest.",
    instructions: [
      "Stand with your feet shoulder-width apart, holding a dumbbell in one hand with your palm facing your body.",
      "Bend your knees slightly and hinge forward at the hips, keeping your back straight and your core engaged.",
      "Let the dumbbell hang straight down towards the floor, with your arm fully extended.",
      "Pull the dumbbell up towards your chest, keeping your elbow close to your body and squeezing your shoulder blades together.",
      "Pause for a moment at the top, then slowly lower the dumbbell back down to the starting position.",
      "Repeat for the desired number of repetitions, then switch sides.",
    ],
  },
  "db-incline-bench-press": {
    id: "db-incline-bench-press",
    name: "Incline DB Press",
    muscleGroup: "chest",
    type: "weighted",
    equipment: "Adjustable bench + dumbbells",
    exerciseDbId: "0314",
    description: "The dumbbell incline bench press targets the upper portion of the pectoral muscles, with additional emphasis on the shoulders and triceps. It is performed on an incline bench.",
    instructions: [
      "Set up an incline bench at a 45-degree angle.",
      "Sit on the bench with your feet flat on the ground and your back pressed firmly against the bench.",
      "Hold a dumbbell in each hand, palms facing forward, and lift them to shoulder height.",
      "Slowly lower the dumbbells to the sides of your chest, keeping your elbows at a 90-degree angle.",
      "Push the dumbbells back up to the starting position, fully extending your arms.",
      "Repeat for the desired number of repetitions.",
    ],
  },
  "cable-seated-row-low": {
    id: "cable-seated-row-low",
    name: "Cable Seated Row (low pulley)",
    muscleGroup: "back",
    type: "weighted",
    equipment: "Functional trainer, low pulley",
    exerciseDbId: "0861",
    description: "The cable low seated row targets the upper back and also engages the biceps and forearms. The movement involves pulling the cable handles toward the torso while squeezing the shoulder blades together.",
    instructions: [
      "Sit on the machine with your feet flat on the footrests and your knees slightly bent.",
      "Grasp the handles with an overhand grip, palms facing down.",
      "Keep your back straight and lean slightly forward, maintaining a slight bend in your elbows.",
      "Pull the handles towards your body, squeezing your shoulder blades together.",
      "Pause for a moment at the peak of the movement, then slowly release back to the starting position.",
      "Repeat for the desired number of repetitions.",
    ],
  },
  "cable-chest-fly-high": {
    id: "cable-chest-fly-high",
    name: "Cable Chest Fly (high pulley)",
    muscleGroup: "chest",
    type: "weighted",
    equipment: "Functional trainer, high pulley",
    exerciseDbId: "0171",
    description: "The cable chest fly targets the pectoral muscles using a cable machine. It emphasizes a wide arc motion to stretch and contract the chest.",
    instructions: [
      "Set the pulleys to shoulder height on both sides of a cable machine.",
      "Stand in the center, grasp a handle in each hand with a slight bend in the elbows.",
      "Step forward slightly to create tension in the cables.",
      "With a controlled motion, bring your hands together in front of your chest in a wide arc.",
      "Pause for a moment at the peak contraction, then slowly return to the starting position.",
      "Repeat for the desired number of repetitions.",
    ],
  },
  "cable-face-pull-high": {
    id: "cable-face-pull-high",
    name: "Cable Face Pull (high pulley)",
    muscleGroup: "rear delts",
    type: "weighted",
    equipment: "Functional trainer, high pulley",
    exerciseDbId: null,
    description: "The cable face pull targets the rear deltoids and external rotators of the shoulder, helping to improve posture and shoulder health.",
    instructions: [
      "Attach a rope to a high pulley cable machine.",
      "Stand facing the machine, grasp both ends of the rope with an overhand grip.",
      "Step back to create tension, keeping your feet shoulder-width apart.",
      "Pull the rope towards your face, separating your hands as they reach your ears.",
      "Squeeze your rear delts and external rotators at the peak.",
      "Slowly return to the starting position under control.",
      "Repeat for the desired number of repetitions.",
    ],
  },
  "kb-swing-light": {
    id: "kb-swing-light",
    name: "KB Swings (light, warmup)",
    muscleGroup: "full body",
    type: "weighted",
    equipment: "20 lb kettlebell",
    exerciseDbId: "0549",
    description: "The kettlebell swing is a dynamic exercise that targets the glutes and also engages the hamstrings and core. It involves swinging a kettlebell between the legs and up to shoulder height using hip drive.",
    instructions: [
      "Stand with your feet shoulder-width apart, toes pointed slightly outward.",
      "Hold the kettlebell with both hands in front of your body, arms extended.",
      "Bend your knees slightly and hinge at the hips, pushing your butt back.",
      "Swing the kettlebell back between your legs, keeping your arms straight and maintaining a flat back.",
      "Drive your hips forward and swing the kettlebell up to shoulder height using the momentum from your hips.",
      "Allow the kettlebell to swing back down between your legs and repeat.",
    ],
  },
  "battle-rope-alt-waves": {
    id: "battle-rope-alt-waves",
    name: "Battle Rope Alternating Waves",
    muscleGroup: "conditioning",
    type: "timed",
    equipment: "Battle rope",
    exerciseDbId: "0128",
    description: "Battle rope alternating waves is a high-intensity conditioning exercise that develops cardiovascular endurance, shoulder strength, and core stability.",
    instructions: [
      "Stand facing the anchor point with feet shoulder-width apart, knees slightly bent.",
      "Hold one end of the rope in each hand with an overhand grip.",
      "Raise one arm to shoulder height, then lower it as you raise the other arm.",
      "Alternate arms rapidly to create a wave pattern in the rope.",
      "Maintain a strong core and athletic stance throughout.",
      "Continue for the target duration.",
    ],
  },
  "dynamic-mobility": {
    id: "dynamic-mobility",
    name: "Dynamic Stretching / Mobility",
    muscleGroup: "mobility",
    type: "timed",
    equipment: "Bodyweight",
    exerciseDbId: null,
    description: "Dynamic stretching and mobility work prepares the body for exercise by increasing blood flow, improving range of motion, and activating key muscle groups.",
    instructions: [
      "Perform leg swings (front-to-back and side-to-side) for 10 reps each leg.",
      "Do hip circles, 10 rotations each direction.",
      "Perform arm circles, 10 forward and 10 backward.",
      "Do bodyweight squats with a 2-second pause at the bottom, 10 reps.",
      "Finish with 10 walkouts or inchworms to stretch the posterior chain.",
      "Move through each drill with control and full range of motion.",
    ],
  },
  "kb-swing-heavy": {
    id: "kb-swing-heavy",
    name: "KB Swings (heavy)",
    muscleGroup: "full body",
    type: "weighted",
    equipment: "35 lb kettlebell",
    exerciseDbId: "0549",
    description: "The heavy kettlebell swing develops explosive hip power, glute strength, and cardiovascular conditioning. Same mechanics as the light swing with greater load.",
    instructions: [
      "Stand with your feet shoulder-width apart, toes pointed slightly outward.",
      "Hold the kettlebell with both hands in front of your body, arms extended.",
      "Bend your knees slightly and hinge at the hips, pushing your butt back.",
      "Swing the kettlebell back between your legs, keeping your arms straight and maintaining a flat back.",
      "Drive your hips forward explosively and swing the kettlebell up to shoulder height.",
      "Allow the kettlebell to swing back down between your legs and repeat.",
    ],
  },
  "battle-rope-slams": {
    id: "battle-rope-slams",
    name: "Battle Rope Slams",
    muscleGroup: "conditioning",
    type: "timed",
    equipment: "Battle rope",
    exerciseDbId: null,
    description: "Battle rope slams are a power-based conditioning exercise targeting the shoulders, core, and full body, building explosive strength and cardiovascular endurance.",
    instructions: [
      "Stand facing the anchor point with feet shoulder-width apart, knees slightly bent.",
      "Hold both rope ends together with both hands overhead.",
      "Slam the ropes down to the ground as hard as possible.",
      "Immediately raise the ropes back overhead to full extension.",
      "Use your whole body — core, arms, and hips — to generate force.",
      "Continue for the target duration.",
    ],
  },
  "kb-goblet-squat": {
    id: "kb-goblet-squat",
    name: "KB Goblet Squat",
    muscleGroup: "quads",
    type: "weighted",
    equipment: "35 lb kettlebell",
    exerciseDbId: "0534",
    description: "The kettlebell goblet squat targets the glutes and quadriceps while holding a kettlebell close to the chest, making it great for building strength and improving squat technique.",
    instructions: [
      "Stand with your feet shoulder-width apart, holding a kettlebell close to your chest with both hands.",
      "Keeping your chest up and core engaged, lower your body into a squat by bending at the knees and hips.",
      "Continue lowering until your thighs are parallel to the ground, or as low as you can comfortably go.",
      "Pause for a moment at the bottom, then push through your heels to return to the starting position.",
      "Repeat for the desired number of repetitions.",
    ],
  },
  "smith-hip-thrust": {
    id: "smith-hip-thrust",
    name: "Smith Machine Hip Thrust",
    muscleGroup: "glutes",
    type: "weighted",
    equipment: "Smith machine, bench",
    exerciseDbId: null,
    description: "The Smith machine hip thrust is a loaded glute exercise performed with the upper back on a bench and the barbell across the hips. It maximally targets the glutes through hip extension.",
    instructions: [
      "Set the Smith machine bar to a height that allows it to rest across your hips when seated on the floor.",
      "Sit on the floor with your upper back against a bench, feet flat and knees bent at about 90 degrees.",
      "Roll the bar over your hips and pad it if needed.",
      "Drive through your heels and squeeze your glutes to thrust your hips up until your body forms a straight line from shoulders to knees.",
      "Pause and squeeze hard at the top, then lower under control.",
      "Repeat for the desired number of repetitions.",
    ],
  },
  "cable-glute-kickback-low": {
    id: "cable-glute-kickback-low",
    name: "Cable Glute Kickback (low pulley)",
    muscleGroup: "glutes",
    type: "weighted",
    equipment: "Functional trainer, low pulley, ankle strap",
    exerciseDbId: null,
    description: "The cable glute kickback isolates the glutes through hip extension with constant cable tension. An ankle strap attachment keeps the load on the glute throughout the full range.",
    instructions: [
      "Attach an ankle strap to the low pulley and fasten it around one ankle.",
      "Stand facing the machine, feet hip-width apart, and hold the frame for balance.",
      "Keeping a slight bend in your standing knee, kick the strapped leg back and up in a controlled arc.",
      "Squeeze the glute hard at the top of the movement.",
      "Slowly return to the starting position without letting your hip flex past neutral.",
      "Complete all reps on one side before switching.",
    ],
  },
  "kb-clean-press": {
    id: "kb-clean-press",
    name: "KB Single-Arm Clean & Press",
    muscleGroup: "full body",
    type: "weighted",
    equipment: "25 lb kettlebell",
    exerciseDbId: "0518",
    description: "The kettlebell single-arm clean and press is a full-body exercise combining a clean (pulling to the rack position) and an overhead press. It builds coordination, explosive power, and shoulder strength.",
    instructions: [
      "Stand with your feet shoulder-width apart, holding a kettlebell in one hand with an overhand grip.",
      "Bend your knees slightly and hinge forward at the hips, allowing the kettlebell to hang in front of you.",
      "In one fluid motion, explosively extend your hips, shrug your shoulder, and pull the kettlebell up towards your shoulder.",
      "As the kettlebell reaches shoulder height, rotate your wrist and catch it in the rack position (resting on the outside of your forearm).",
      "From the rack position, press the kettlebell overhead by extending your arm fully.",
      "Lower the kettlebell back to the rack position, then back to the starting position.",
      "Repeat for the desired number of repetitions, then switch arms.",
    ],
  },
};

export function getExercise(id: string) {
  const ex = exercises[id];
  if (!ex) throw new Error(`Unknown exercise: ${id}`);
  return ex;
}
